# Generated by Django 2.2.7 on 2019-12-01 18:35

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('apply_type', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('others', 'Others')], default='clt', max_length=200, verbose_name='Apply Type')),
                ('how_to_apply', models.TextField(blank=True, null=True, verbose_name='How to Apply')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('remote_type', models.CharField(choices=[('full_remote', '100% Remote'), ('partial_remote', 'Partial Remote'), ('onsite', 'On-Site')], default='onsite', max_length=200, verbose_name='Remote Type')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ('-updated_at',),
            },
        ),
    ]
